sonar.projectKey=nafissa-frontend
sonar.projectName=NAFISSATOU Frontend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
# sonar.token=sqp_VOTRE_TOKEN_ICI
sonar.sources=src
sonar.language=js
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,src/test/**
sonar.sourceEncoding=UTF-8
