sonar.projectKey=NAFISSA-Platform
sonar.projectName=Plateforme NAFISSA
sonar.sourceEncoding=UTF-8

sonar.sources=backend-node/src,frontend/src,mobile/app,mobile/components,mobile/constants,mobile/context,mobile/lib
sonar.tests=backend-node/src,frontend/src/test
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/build/**,**/.expo/**,**/prisma/migrations/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.webp,**/*.svg

sonar.javascript.lcov.reportPaths=backend-node/coverage/lcov.info,frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=mobile/tsconfig.json