sonar.projectKey=nafissa-platform
sonar.projectName=NAFISSA Platform
sonar.projectVersion=1.0.0

# IMPORTANT pour SonarCloud
sonar.organization=sysamba
sonar.host.url=https://sonarcloud.io

# Sources
sonar.sources=backend-node/src,frontend/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/*.test.js,**/*.test.jsx,**/src/test/**,**/prisma/migrations/**

# Coverage (IMPORTANT)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend-node/coverage/lcov.info

sonar.sourceEncoding=UTF-8